#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - name: Clean global cache
      run: npm cache clean --force
    - name: Set up Node
      uses: actions/checkout@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: CI build & test
      run: |
        npm run build --if-present
        npm test
      env:
        CI: true
